### ISSUE TITLE
Issue with PassionFruit

### ISSUE THREAD

**Issue by chackokavanattu12** [chaitin/passionfruit#56] opened 2019-08-22 04:40 UTC
Hi Guys,

I am finding the following issues,

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/12.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v12.9.0/lib/node_modules/passionfruit/node_modules/frida/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v12.9.0/lib/node_modules/passionfruit/node_modules/frida/.node-gyp'
gyp ERR! System Linux 4.14.0-kali3-amd64
gyp ERR! command "/root/.nvm/versions/node/v12.9.0/bin/node" "/root/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v12.9.0/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/passionfruit/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.6.16 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.6.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-22T03_58_02_206Z-debug.log
root@startr3k:~# npm install node-gyp-build

npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by ChiChou** [comment] 2019-08-22 04:44
Duplicate of #45

This is due to frida may not have the prebuilt package for latest node yet. Please use Long Term Support (LTS, currently 10.16.3)

**Closed by ChiChou** 2019-08-22 04:44 UTC

**Comment by ChiChou** [comment] 2019-08-22 04:45
This is due to frida may not have the prebuilt package for latest node yet. Please use Long Term Support (LTS, currently 10.16.3)
