### ISSUE TITLE
Issue launching app analysis on 32 bit devices

### ISSUE THREAD

**Issue by eric1dat** [chaitin/passionfruit#14] opened 2018-01-05 22:37 UTC
I am having and issue where in, when I launch an app analysis on a 32 bit device.  The process begins, spins a bit then restarts the device.  I initially thouht it was an issue with frida,  when I select the device I see all the apps avalible on it and I believe this a frida process as well.  It is when I launch the app that things fail.  I am able to run from the same server instace on 64 bit devices no problem.  One more difference between 32 and 64 bit devices the 64 bit devices are jailbroken 9.3.3 and the 32 bit devices are 9.3.5 jailbrakes.

**Comment by ChiChou** [comment] 2018-01-06 07:51
Any log from Console.app?

**Comment by eric1dat** [comment] 2018-01-06 14:24
Yes on the the error, here's whats going to the Console
==========================================
An unhandled Rejection occurred:
Rejection:Error:The Connection is closed
Error: The Connection is closed
==========================================

Thanks for the app and having a look at this.

**Comment by ChiChou** [comment] 2018-01-06 16:37
`open Console.app`, I mean the log from iPhone

**Comment by eric1dat** [comment] 2018-01-07 22:27
Ah,  O.k.  The device is at the office,  I'll dump the logs from it when I get in tomorrow.

**Comment by eric1dat** [comment] 2018-01-08 15:53
Find attached the log from me running the process this morning 
[DeviceCrash.crash.zip](https://github.com/chaitin/passionfruit/files/1612143/DeviceCrash.crash.zip)

**Comment by ChiChou** [comment] 2018-01-09 07:52
`launchd` crashed, looks like it's a jailbreak environment problem

**Comment by ChiChou** [comment] 2018-01-09 07:53
Passionfruit also supports repacking `FridaGadget.dylib` to ipa, which does not require jailbroken device.

**Comment by eric1dat** [comment] 2018-01-09 12:39
Thanks for the research.  I’ll try injecting the Frida library or a different 9.3.5 jailbreak

**Comment by ChiChou** [comment] 2018-01-18 07:17
I only got a 32bit iPhone 5 with iOS 8. Still unable to reproduce this.

**Comment by eric1dat** [comment] 2018-01-19 23:18
Wow, that's interesting.  Perhaps it is my Jailbreak.  I am using the Phoenix Jailbreak on 3 different 9.3.5 device.  Again thanks much for your efforts.

**Comment by allRiceOnMe** [comment] 2018-02-22 08:15
I have the same issue with the Phoenix Jailbreak (iOS 9.3.5, iPhone4S).

**Comment by ChiChou** [comment] 2018-02-22 08:24
Yet another question to ask, have you confirm that the frida on device is properly installed? There's both 32bit and 64bit version in the Cydia source:

![img_0125](https://user-images.githubusercontent.com/2802045/36527487-e7b64c54-17ec-11e8-97a4-ea178563dc8c.PNG)

**Comment by allRiceOnMe** [comment] 2018-02-22 08:55
Yea, i know. It's the correct "Frida for 32-bit devices" version installed. `frida-ps -U` shows all processes and attaching works fine.

**Comment by ChiChou** [comment] 2018-02-22 09:23
@allRiceOnMe Does `frida -f [com.xxx.bundleid.goes.here] -U` work?

**Comment by allRiceOnMe** [comment] 2018-02-22 09:32
Nope, it doesn't. Same result as when using passionfruit: The device restarts.

**Comment by ChiChou** [comment] 2018-02-22 09:44
I guess only @oleavr can solve this...

Anyway, you can manually start an app on device, then passionfruit will try to attach it instead of spawning a new instance.

**Comment by ChiChou** [comment] 2018-02-22 10:43
Seems like it's a frida framework's bug: https://github.com/frida/frida/issues/373
@eric1dat

**Comment by eric1dat** [comment] 2018-02-26 19:25
Launching the app on the device then attaching with the tool works fine.  Thanks for everyones inputs.

**Comment by oleavr** [comment] 2018-02-26 19:27
This is indeed a bug in Frida, but I'm afraid I won't fix this unless somebody volunteers their time to debug it – I don't have any 32-bit devices available for testing.

**Comment by ChiChou** [comment] 2018-02-27 03:23
cc @allRiceOnMe

**Comment by allRiceOnMe** [comment] 2018-02-27 10:34
@oleavr How can I help?

**Comment by oleavr** [comment] 2018-02-27 11:52
@allRiceOnMe Would be great if you could build Frida yourself, changing `config.mk` to remove `--strip`, and replacing `/usr/sbin/frida-server` with your symbolicated version. (Make sure you `rm` the original file first to avoid code-signing issues.) Then use `launchctl` to `unload` and then `load` frida-server. Once that's done, the next step is figuring out why `launchd` crashes when we instrument it with [this script](https://github.com/frida/frida-core/blob/master/src/darwin/agent/launchd.js).

**Comment by allRiceOnMe** [comment] 2018-02-27 13:32
@oleavr Could you please name the full command to `load` and `unload` using `launchctl`?

**Comment by oleavr** [comment] 2018-02-27 14:30
@allRiceOnMe 

```sh
$ launchctl unload /Library/LaunchDaemons/re.frida.server.plist
$ launchctl load /Library/LaunchDaemons/re.frida.server.plist
```

**Comment by allRiceOnMe** [comment] 2018-02-27 14:48
@oleavr Ok, perfekt. I'm prepared.

**Comment by allRiceOnMe** [comment] 2018-02-28 09:11
@oleavr What would be the next step? Thanks in advance

**Comment by oleavr** [comment] 2018-02-28 11:45
@allRiceOnMe Could you provide a disassembly of `__posix_spawn`? We hook it [here](https://github.com/frida/frida-core/blob/b46081304f904773882f6efac4507c627a38fcdb/src/darwin/agent/launchd.js#L42). I'm also curious if you are able to trace it if you do `frida-trace -U -p 1 -i __posix_spawn` -- does that crash launchd (PID 1) when you manually launch an app, or does it work?

**Comment by ChiChou** [comment] 2018-07-08 06:29
Looks like

**Closed by ChiChou** 2018-07-08 06:29 UTC
Labels: wontfix
